# Setup
title:               Sam Hirshman
tagline:             
url:                 https://samhirshman.com
baseurl:             https://samhirshman.com

#Pages for header  
pages_list:       
  Contact: 'mailto:shirshma@chicagobooth.edu'
  Coffee: '/docs/interests'
  CV: '/public/CV1.pdf'
  Research: '/docs/research'


# Assets 
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :default

# About/contact
author:              
  name:              shirshman
  url:               shirshma.github.io


# Gems
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag

#links
links:
  -link1:
    url: https://www.timwendelboe.no/
  

theme: jekyll-theme-slate
