# Setup
title:               Sam Hirshman
tagline:             
url:                 https://samhirshman.com
baseurl:             https://samhirshman.com

#Pages for header  
pages_list:       
  Contact: 'mailto:shirsma@chicagobooth.edu'
  Interests: '/interests.md'
  CV: '/public/CV.pdf'


# Assets 
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:              
  name:              shirshman
  url:               shirshma.github.io


# Gems
gems:
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-seo-tag

